### ISSUE TITLE
Implement a Generational Garbage Collector

### ISSUE THREAD

**Issue by Techcable** [DuckLogic/zerogc#14]
Implement a heavy-duty [generational garbage collector](https://en.wikipedia.org/wiki/Tracing_garbage_collection#Generational_GC_(ephemeral_GC)). This should significantly improve performance for applications where allocations are frequent. It is intended primarily for use in language VMs and JITs (#12).

## Tasks
- [ ] Basic Implementation
- [ ] Use card tables for efficient write barriers
- [ ] Extremely efficent bump-pointer allocation for new generation
  - [ ] Properly relocate pointers
- [ ] Handle "humongous objects" properly
   - Most GCs allocate very large objects (4KB+) directly into a dedicated space, bypassing the new generation
